app: jibot
service: jibot

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"
functions:
  bot:
    handler: app/handler.bot
    events:
      - http:
          path: /
          method: post
  lookup:
    handler: app/handler.lookup
    events:
      - http:
          path: /lookup
          method: get

plugins:
  - serverless-plugin-typescript
